@baseUrl = http://demo.local
@token = test

### Get actions
GET {{baseUrl}}/actions/get
Authorization: Bearer {{token}}

###

### Set action1 (reboot)
POST {{baseUrl}}/actions/set
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "action": "reboot"
}

###

### Set action2 tft
POST {{baseUrl}}/actions/set
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "action": "tft",
  "message": "Hello World!"
}

###