@baseUrl = http://demo.local

### Get actions
GET {{baseUrl}}/actions/get

###

### Set actions
POST {{baseUrl}}/actions/save
Content-Type: application/json

{
  "ssid": "demo",
  "password": "example"
}

###