@baseUrl = http://demo2.local
@token = test

### send command1
POST {{baseUrl}}/command/set
Authorization: Bearer {{token}}
Content-Type: application/json

hid keys1 test
###

### send command2
POST {{baseUrl}}/command/set
Authorization: Bearer {{token}}
Content-Type: application/json

script file /1.txt
###
