@baseUrl = http://demo1.local
@token = test

### backup
GET {{baseUrl}}/device/backup
Authorization: Bearer {{token}}

###

### Get
GET {{baseUrl}}/device/info
Authorization: Bearer {{token}}

###

### Get
GET {{baseUrl}}/device/wifi/networks
Authorization: Bearer {{token}}

###

### Get
GET {{baseUrl}}/device/reboot
Authorization: Bearer {{token}}

###