@baseUrl = http://demo2.local
@token = test

### Get files (list all files)
GET {{baseUrl}}/files
Authorization: Bearer {{token}}

###

### Create a new file
POST {{baseUrl}}/file?filename=/test.txt
Authorization: Bearer {{token}}
Content-Type: text/plain

This is the content of the new file.

###

### Create a new file
POST {{baseUrl}}/file?filename=/test2.txt
Authorization: Bearer {{token}}
Content-Type: text/plain

This is the content of the new file.

###

### Create a new file with path
POST {{baseUrl}}/file?filename=/hello/test1.txt
Authorization: Bearer {{token}}
Content-Type: text/plain

Hello path1.

###

### Create a new file with path
POST {{baseUrl}}/file?filename=/hello/test2.txt
Authorization: Bearer {{token}}
Content-Type: text/plain

Hello path2.

###

### Read a file 1
GET {{baseUrl}}/file?filename=/test.txt
Authorization: Bearer {{token}}

###

### Read a file path
GET {{baseUrl}}/file?filename=/hello/test.txt
Authorization: Bearer {{token}}

###

### Read a file 2
GET {{baseUrl}}/file?filename=/settings.json
Authorization: Bearer {{token}}

###

### Read a file 3
GET {{baseUrl}}/file?filename=/wifi_networks.json
Authorization: Bearer {{token}}

###

### Append content to an existing file
POST {{baseUrl}}/file?filename=/test.txt
Authorization: Bearer {{token}}
Content-Type: text/plain

This is additional content appended to the file.

###

### Delete a file
DELETE {{baseUrl}}/file?filename=/test.txt
Authorization: Bearer {{token}}

###

### Delete a file path
DELETE {{baseUrl}}/file?filename=/hello/test2.txt
Authorization: Bearer {{token}}

###

### Error case: Attempt to read a non-existent file
GET {{baseUrl}}/file?filename=/nonexistent.txt
Authorization: Bearer {{token}}

###

### Error case: Attempt to delete a non-existent file
DELETE {{baseUrl}}/file?filename=/nonexistent.txt
Authorization: Bearer {{token}}
