@baseUrl = http://demo2.local
@token = test

### Test1
POST {{baseUrl}}/file?filename=/a.txt
Authorization: Bearer {{token}}
Content-Type: text/plain

REM Start of script
DEFAULTDELAY 500

REM Say hello
TEMPLATE HELLO
DELAY 1000

REM Repeat the following block 3 times
TEMPLATE DEBUG
REPEAT 3

REM End of script
###

### Test2
POST {{baseUrl}}/file?filename=/b.txt
Authorization: Bearer {{token}}
Content-Type: text/plain

REM Start of script

led brightness 255

led color purple
DELAY 1000

led color blue
DELAY 1000

REPEAT 30

REM End of script
###

### Test3
POST {{baseUrl}}/file?filename=/c.txt
Authorization: Bearer {{token}}
Content-Type: text/plain

REM Start of script
DEFAULTDELAY 500

REM Say hello
TEMPLATE HELLO
DELAY 1000

REM Repeat the following block 3 times
TEMPLATE DEBUG
REPEAT 3

REM End of script
###

### Test4
POST {{baseUrl}}/file?filename=/1.txt
Authorization: Bearer {{token}}
Content-Type: text/plain

REM Start of script
DEFAULTDELAY 1000
led color green
led color blue
hid keys1 hello
REPEAT 3

REM End of script
###