@baseUrl = http://demo.local
#@baseUrl = http://192.168.4.1

### Get settings
GET {{baseUrl}}/settings/get

###

### Set settings
POST {{baseUrl}}/settings/set
Content-Type: application/json

{
  "wifi_ssid": "ssid",
  "wifi_password": "password"
}

###