@baseUrl = http://demo2.local
@token = test

### Get settings
GET {{baseUrl}}/settings/get
Authorization: Bearer {{token}}

###

### Set settings
POST {{baseUrl}}/settings/set
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "device_name": "demo",
  "wifi_ssid": "ssid1",
  "wifi_password": "password",
  "mqtt_server": "mqtt.server",
  "mqtt_port": 1883,
  "mqtt_user": "user",
  "mqtt_password": "password",
  "api_key": "password"
}

###