@baseUrl = http://demo.local

### GET wifi networks
GET {{baseUrl}}/wifi/get

###

### Set settings
POST {{baseUrl}}/wifi/save
Content-Type: application/json

{
  "wifi_ssid": "demo",
  "wifi_password": "example"
}

###