@baseUrl = http://demo.local
#@baseUrl = http://192.168.4.1

### GET wifi networks
GET {{baseUrl}}/wifi/get

###

### Set settings
POST {{baseUrl}}/wifi/save
Content-Type: application/json

{
  "wifi_ssid": "ssid",
  "wifi_password": "password"
}

###