name: GitHub Pages Deployment

on:
  workflow_run:
    workflows:
      - PlatformIO Build and Release
    types:
      - completed

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download firmware artifact
        uses: actions/download-artifact@v3
        with:
          name: firmware

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move firmware to site
        run: |
          mkdir -p site/public/firmware
          mv test.bin site/public/firmware/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: site
        run: npm install

      - name: Clean dist folder
        run: rm -rf site/dist

      - name: Build website
        working-directory: site
        run: NODE_ENV=production npm run build

      - name: Debug list firmware in site
        run: ls -R site/public/firmware

      - name: Debug list build output
        run: ls -R site/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/dist
